<?php
$availableRooms=array_values(array_filter($rooms,fn($r)=>$r['status']==='Disponível'));
$monthly=count(array_filter($all,fn($b)=>substr($b['date'],0,7)===date('Y-m')&&in_array($b['status'],['Confirmado','Pendente'],true)));
$weekCount=count(array_filter($active,fn($b)=>$b['date']<=date('Y-m-d',strtotime('sunday this week'))));
$next=$active[0]['date']??null;
$nextLabel=$next?($next===date('Y-m-d')?'Hoje':($next===date('Y-m-d',strtotime('+1 day'))?'Amanhã':date('d/m',strtotime($next)))):'—';
$days=['Domingo','Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado'];$months=['janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'];
?>
<section class="welcome-banner"><img src="public/assets/images/scene-8.jpg" alt="Sala de aula"><div class="welcome-copy"><p><?= e($days[(int)date('w')].', '.date('d').' de '.$months[(int)date('n')-1].' de '.date('Y')) ?></p><h2><?= (int)date('H')<12?'Bom dia':((int)date('H')<18?'Boa tarde':'Boa noite') ?>, <?= e(explode(' ',$currentUser['name'])[0]) ?>!</h2><p>Você tem <strong><?= $weekCount ?> reservas</strong> ativas esta semana.</p></div><a class="button button-white" href="<?= e(url('rooms')) ?>"><?= icon('plus') ?>Nova Reserva</a></section>
<section class="stat-grid teacher-stats" aria-label="Resumo de reservas"><?php foreach([['calendar-days',$monthly,'Reservas este mês'],['clock',$nextLabel,'Próxima reserva'],['door-open',count($availableRooms),'Salas disponíveis']] as [$i,$value,$label]): ?><article class="stat-card"><span class="stat-icon"><?= icon($i) ?></span><div><strong><?= e($value) ?></strong><p><?= e($label) ?></p></div></article><?php endforeach; ?></section>
<div class="dashboard-grid"><section class="card"><header class="card-heading"><h3>Próximas reservas</h3><a class="text-link" href="<?= e(url('reservations')) ?>">Ver todas <?= icon('chevron-right') ?></a></header><?php if(!$active){empty_state('Nenhuma reserva próxima','Explore as salas e solicite sua primeira reserva.');}foreach(array_slice($active,0,3) as $b): ?><article class="reservation-row"><div class="date-tile"><strong><?= date('d',strtotime($b['date'])) ?></strong><small>/<?= date('m',strtotime($b['date'])) ?></small></div><div class="grow"><div class="row-title"><h4><?= e($b['room_name']) ?></h4><?= badge($b['status']) ?></div><p><?= e($b['purpose']) ?></p><small class="inline-meta"><?= icon('clock') ?><?= e(substr($b['start_time'],0,5).' – '.substr($b['end_time'],0,5)) ?></small></div></article><?php endforeach; ?></section>
<section class="card"><header class="card-heading"><h3>Salas disponíveis agora</h3></header><?php foreach(array_slice($availableRooms,0,4) as $room): ?><a class="available-row" href="<?= e(url('rooms',['action'=>'show','id'=>$room['id']])) ?>"><?= icon(room_icon($room['type'])) ?><div class="grow"><h4><?= e($room['name']) ?></h4><small><?= (int)$room['capacity'] ?> pessoas · <?= e($room['floor']) ?></small></div><?= icon('chevron-right') ?></a><?php endforeach; if(!$availableRooms){empty_state('Nenhuma sala disponível','Confira o catálogo para mais informações.');} ?></section></div>
