<?php require_once __DIR__.'/helpers.php'; $subtitle??='Gestão escolar integrada'; ?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#1a3150"><title><?= e($title) ?> · SalaHub</title><link rel="icon" href="public/assets/logo.svg" type="image/svg+xml"><link rel="stylesheet" href="public/assets/app.css"><script src="public/assets/app.js" defer></script></head>
<body class="<?= $admin?'admin-view':'teacher-view' ?>"><a class="skip-link" href="#main">Pular para o conteúdo</a>
<aside class="sidebar" id="sidebar"><a class="brand" href="<?= e(url()) ?>"><img src="public/assets/logo-dark.svg" width="36" height="36" alt=""><span><strong>SalaHub</strong><small><?= $admin?'Coordenação':'Professor' ?></small></span></a>
<nav aria-label="Navegação principal">
<?php $nav=$admin?['dashboard'=>['layout-grid','Painel'],'rooms'=>['door-open','Salas'],'approvals'=>['book-open','Aprovações'],'calendar'=>['calendar-days','Calendário']]:['dashboard'=>['layout-grid','Início'],'rooms'=>['door-open','Salas'],'reservations'=>['calendar-days','Minhas Reservas'],'tickets'=>['ticket','Meus Chamados']]; foreach($nav as $key=>[$i,$label]): ?>
<a class="nav-link <?= $page===$key?'active':'' ?>" <?= $page===$key?'aria-current="page"':'' ?> href="<?= e(url($key)) ?>"><?= icon($i) ?><span><?= e($label) ?></span></a>
<?php endforeach; if($admin): ?><div class="nav-caption">GESTÃO</div><?php foreach(['users'=>['users','Usuários'],'tickets'=>['ticket','Chamados'],'categories'=>['tags','Categorias']] as $key=>[$i,$label]): ?><a class="nav-link <?= $page===$key?'active':'' ?>" href="<?= e(url($key)) ?>" <?= $page===$key?'aria-current="page"':'' ?>><?= icon($i) ?><?= e($label) ?></a><?php endforeach; endif; ?>
</nav><div class="sidebar-bottom"><a class="nav-link <?= $page==='settings'?'active':'' ?>" href="<?= e(url('settings')) ?>"><?= icon('settings') ?>Configurações</a><form method="post" action="<?= e(url('logout',['action'=>'store'])) ?>"><?= csrf_field() ?><button class="nav-link"><?= icon('log-out') ?>Sair</button></form></div></aside>
<div class="app-shell"><header class="topbar"><button class="icon-button mobile-menu" aria-label="Abrir menu" aria-controls="sidebar" aria-expanded="false"><?= icon('menu') ?></button><div class="page-heading"><h1><?= e($title) ?></h1><p><?= e($subtitle) ?></p></div><div class="header-actions">
<?php if(\App\Core\Auth::isAdmin()): ?><form method="post" action="<?= e(url('switch',['action'=>'store'])) ?>"><?= csrf_field() ?><button class="button button-small button-outline view-switch"><?= icon('graduation-cap') ?><span>Ver como <?= $admin?'Professor':'Admin' ?></span></button></form><?php endif; ?>
<details class="notifications"><summary aria-label="Notificações"><?= icon('bell') ?><?php if($notifications): ?><span class="notification-count"><?= count($notifications) ?></span><?php endif; ?></summary><div class="notification-panel"><h3><?= $admin?'Solicitações pendentes':'Suas reservas' ?></h3><?php if(!$notifications): ?><p>Nenhuma notificação por enquanto.</p><?php else: foreach($notifications as $notice): ?><a href="<?= e(url($admin?'approvals':'reservations')) ?>"><strong><?= e($notice['room_name']) ?></strong><small><?= e(date_br($notice['date'])) ?> · <?= e($notice['status']) ?></small></a><?php endforeach; endif; ?></div></details>
<a class="profile" href="<?= e(url('settings')) ?>"><span class="avatar"><?= e(initials($currentUser['name'])) ?></span><span class="profile-name"><strong><?= e($currentUser['name']) ?></strong><small><?= $admin?'Coordenação':'Professor(a)' ?></small></span></a></div></header>
<main id="main" class="content" tabindex="-1"><?php if($flash): ?><div class="alert toast" role="status"><?= icon($flash['type']==='error'?'circle-alert':'check') ?><span><?= e($flash['message']) ?></span><button class="icon-button" data-dismiss aria-label="Fechar mensagem"><?= icon('x') ?></button></div><?php endif; ?><?php require __DIR__.'/'.$view.'.php'; ?></main></div>
<dialog id="confirm-dialog"><form method="dialog"><div class="dialog-icon"><?= icon('circle-alert') ?></div><h2>Confirmar ação</h2><p id="confirm-message"></p><div class="form-actions"><button value="cancel" class="button button-outline">Voltar</button><button value="confirm" class="button">Confirmar</button></div></form></dialog>
</body></html>

