<?php require_once __DIR__.'/helpers.php'; ?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bem-vindo · SalaHub</title><link rel="icon" href="public/assets/logo.svg"><link rel="stylesheet" href="public/assets/app.css"><script defer src="public/assets/app.js"></script></head><body class="login-page">
<main class="login-panel"><div class="login-inner"><a class="brand login-brand" href="<?= e(url('login')) ?>"><img src="public/assets/logo.svg" width="40" height="40" alt="SalaHub"><span><strong>SalaHub</strong><small>Sistema Escolar</small></span></a><h1>Bem-vindo de volta</h1><p class="login-intro">Acesse com suas credenciais institucionais.</p>
<?php if($error): ?><div class="alert" role="alert"><?= e($error) ?></div><?php endif; ?>
<form action="<?= e(url('login',['action'=>'store'])) ?>" method="post" class="login-form"><?= csrf_field() ?><div class="field"><label for="email">E-mail institucional</label><input type="email" id="email" name="email" value="<?= e($email) ?>" autocomplete="username" maxlength="190" required></div><div class="field"><label for="password">Senha</label><div class="password-input"><input type="password" id="password" name="password" autocomplete="current-password" required maxlength="72" placeholder="Digite sua senha"><?= password_toggle('password') ?></div></div><div class="login-options"><label class="checkbox"><input type="checkbox" name="remember" value="1"> Manter conectado</label><button class="text-button" type="button" data-open="recovery-dialog">Esqueci a senha</button></div><button class="button full" type="submit" name="portal" value="teacher">Entrar como Professor</button><button class="button button-outline full" type="submit" name="portal" value="admin">Entrar como Coordenação</button></form>
<?php if(app_config('demo_mode')): ?><details class="demo-help"><summary>Acessos para demonstração</summary><p>Senha: <strong>SalaHub@2026</strong></p><p>Professor: ana.lima@escola.edu.br<br>Coordenação: maria.santos@escola.edu.br</p><button type="button" class="text-button" data-demo="teacher">Usar professor</button><span> · </span><button type="button" class="text-button" data-demo="admin">Usar coordenação</button></details><?php endif; ?><p class="login-footer"><?= e(app_config('school_name')) ?> • <?= date('Y') ?></p></div></main>
<aside class="login-hero"><img src="public/assets/images/sesifrente.webp" alt="Fachada da Escola SESI Paraguaçu Paulista"><div class="login-hero-shade"></div><div class="login-hero-content"><h2>Organize os espaços.<br>Potencialize o<br>aprendizado.</h2><p>Reserve salas, laboratórios e auditórios em<br class="desktop-only"> minutos. Sem conflitos, sem burocracia.</p><div class="login-metrics"><div><strong>24</strong><span>Ambientes</span></div><div><strong>600+</strong><span>Reservas/mês</span></div><div><strong>80</strong><span>Professores</span></div></div></div></aside>
<dialog id="recovery-dialog"><form method="dialog"><div class="dialog-icon"><?= icon('shield-check') ?></div><h2>Recuperar acesso</h2><p>Entre em contato com a coordenação da escola para redefinir sua senha. Um administrador pode atualizar seu acesso em <strong>Usuários → Editar</strong>.</p><button class="button full">Entendi</button></form></dialog></body></html>



